server:
  port: 8081
  servlet:
    context-path: /dataservice

spring:
  application:
    name: dataservice
  threads:
    virtual:
      enabled: true


app:
  model:
    default-threshold: 0.75         # O Spring mapeia para defaultThreshold
    version: "v4.2.0-beta"          # O Spring mapeia para version
    path: "/mnt/models/fraud.onnx"  # O Spring mapeia para path